### ISSUE TITLE
Parse library info from source project.

### ISSUE THREAD

**Issue by ShaneDelmore** [ShaneDelmore/imclipitly#6]

**Comment by olafurpg** [comment]
What would be the use-case for this? The sbt plugin can btw extract task/settings from the build and pass it in as command line arguments

**Comment by ShaneDelmore** [comment]
The advice generating code currently uses stub values for these values required by clippy:
https://github.com/ShaneDelmore/imclipitly/blob/master/imclipitly-core/src/main/scala/imclipitly/Codegen.scala#L85

**Comment by ShaneDelmore** [comment]
Great idea, the sbt-buildinfo information should be exactly what I need.

**Comment by olafurpg** [comment]
You don't need sbt-buildinfo, what I had in mind was to add fields to the CodegenOption case class and then pass them in from the ImclipitlyPlugin from here https://github.com/ShaneDelmore/imclipitly/blob/2b2a310acad1304e2765e74405c5c5bc776490a5/imclipitly-sbt/src/main/scala/imclipitly/ImclipitlyPlugin.scala#L114 You can extract `name.value`, `version.value` as well as `libraryDependencies.value`

**Comment by ShaneDelmore** [comment]
I like it. I'll try to add it tonight, then get back to figuring out publishing.

**Comment by ShaneDelmore** [comment]
Implemented in https://github.com/ShaneDelmore/imclipitly/pull/15
